name: Run Multiple Shell Commands

on: push

jobs:
  debug-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Run multiple Linux commands
        run: |
          echo "Current Date and Time:"
          date

          echo "Current Working Directory:"
          pwd

          echo "List of Files:"
          ls -la

          echo "Current User:"
          whoami

          echo "OS Information:"
          uname -a